kubernetes:
  kubeconfig: ~/.kube/config
  in_cluster: false
  qps: 10.0
  burst: 20
  timeout: 20s

api_server:
  enabled: true
  host: "0.0.0.0"
  port: 8080
  enable_swagger: true
  security:
    rate_limit_requests_per_second: 1
    max_connections_per_ip: 10
    idle_timeout_seconds: 120
    read_timeout_seconds: 10
    write_timeout_seconds: 30
    disable_keepalive: false
  swagger_ui:
    enabled: true
    cors_enabled: true
    cors_allow_origin: "*"
    cors_allow_methods: "GET, POST, PUT"
    cors_allow_headers: "Content-Type, Authorization"
    cors_max_age: 3600
    use_strict_csp: false

informer:
  enabled: true
  namespace: default
  resync_period: 2m
  label_selector: environment=production
  field_selector: metadata.name=important-deployment
  logging:
    enable_event_logging: true
    log_level: debug
  workers:
    count: 2

controller_runtime:
  leader_election:
    enabled: true
    id: k8s-custom-controller-leader-election
    namespace: default
  metrics:
    bind_address: :8081

logging:
  level: trace
  format: text

